COLORS:
  事業: {b: 0.8, h: 0.34, s: 1.0}
  刑事: {b: 0.8, h: 0.02, s: 1.0}
  労働: {b: 0.8, h: 0.38, s: 1.0}
  厚生: {b: 0.8, h: 0.58, s: 1.0}
  司法: {b: 0.8, h: 0.8, s: 1.0}
  商業: {b: 0.8, h: 0.36, s: 1.0}
  国会: {b: 0.8, h: 0.1, s: 1.0}
  国債: {b: 0.8, h: 0.44, s: 1.0}
  国土開発: {b: 0.8, h: 0.32, s: 1.0}
  国家公務員: {b: 0.8, h: 0.3, s: 1.0}
  国有財産: {b: 0.8, h: 0.14, s: 1.0}
  国税: {b: 0.8, h: 0.24, s: 1.0}
  土地: {b: 0.8, h: 0.42, s: 1.0}
  地方自治: {b: 0.8, h: 0.6, s: 1.0}
  地方財政: {b: 0.8, h: 0.7, s: 1.0}
  外事: {b: 0.8, h: 0.98, s: 1.0}
  外国為替・貿易: {b: 0.8, h: 0.56, s: 1.0}
  工業: {b: 0.8, h: 0.26, s: 1.0}
  建築・住宅: {b: 0.8, h: 0.92, s: 1.0}
  憲法: {b: 0.8, h: 0.0, s: 1.0}
  教育: {b: 0.8, h: 0.54, s: 1.0}
  文化: {b: 0.8, h: 0.64, s: 1.0}
  林業: {b: 0.8, h: 0.94, s: 1.0}
  民事: {b: 0.8, h: 0.9, s: 1.0}
  水産業: {b: 0.8, h: 0.06, s: 1.0}
  河川: {b: 0.8, h: 0.72, s: 1.0}
  海運: {b: 0.8, h: 0.76, s: 1.0}
  消防: {b: 0.8, h: 0.22, s: 1.0}
  災害対策: {b: 0.8, h: 0.82, s: 1.0}
  環境保全: {b: 0.8, h: 0.48, s: 1.0}
  産業通則: {b: 0.8, h: 0.74, s: 1.0}
  社会保険: {b: 0.8, h: 0.78, s: 1.0}
  社会福祉: {b: 0.8, h: 0.68, s: 1.0}
  統計: {b: 0.8, h: 0.5, s: 1.0}
  航空: {b: 0.8, h: 0.86, s: 1.0}
  行政手続: {b: 0.8, h: 0.4, s: 1.0}
  行政組織: {b: 0.8, h: 0.2, s: 1.0}
  観光: {b: 0.8, h: 0.08, s: 1.0}
  警察: {b: 0.8, h: 0.12, s: 1.0}
  財務通則: {b: 0.8, h: 0.04, s: 1.0}
  貨物運送: {b: 0.8, h: 0.96, s: 1.0}
  農業: {b: 0.8, h: 0.84, s: 1.0}
  道路: {b: 0.8, h: 0.62, s: 1.0}
  郵務: {b: 0.8, h: 0.18, s: 1.0}
  都市計画: {b: 0.8, h: 0.52, s: 1.0}
  金融・保険: {b: 0.8, h: 0.46, s: 1.0}
  鉱業: {b: 0.8, h: 0.16, s: 1.0}
  防衛: {b: 0.8, h: 0.88, s: 1.0}
  陸運: {b: 0.8, h: 0.66, s: 1.0}
  電気通信: {b: 0.8, h: 0.28, s: 1.0}
NODE_BORDER: true
